@startuml
'https://plantuml.com/class-diagram


class Board {
}
class Bank {
}
class Player{
}
class Account {
}
class Game {
}
class ChanceCard {
}
class Die {
}

Player "3..6" -- "1" Bank
Player "1" o-- "1" Account
Die "2" -- "1" Game
Game "1" -- "3..6" Player
Game "1" -- "1" Board
ChanceCard "*" -- "1" Board


@enduml