@startuml
'https://plantuml.com/class-diagram

object Board
object MatadorGame
object Field
object Player
object Die
object ChanceCards



Board"1"--"1"MatadorGame: Played with
Board"1"--"40"Field
Player"3..6"--"1"MatadorGame: played by
Die"2"--"1"MatadorGame: Uses
Board"1"--"0..*"ChanceCards: Has
Field"1"--"0.1"Player: can own
@enduml