@startuml
'https://plantuml.com/class-diagram


object Board {
}
object Bank {
}
object Player{
}
object Account {
}
object Game {
}
object ChanceCard {
}
object Die {
}
object Field{
}
object Ferry{
}
object Deed{

}
object GoToJail


Player "3..6" -- "1" Bank
Player "1" o-- "1" Account
Die "2" -- "1" Game
Game "1" -- "3..6" Player
Game "1" -- "1" Board
ChanceCard "*" -- "1" Board
Board "1" o-- "2" Ferry


@enduml