@startuml
'https://plantuml.com/sequence-diagram

autonumber
->Player: Take turn
Player->System: Roll die
Player<--System: Return result
Player<-System: Move player
Player->System: Take action when landing on field
Player<-System: Return given action and inform player about result


@enduml