@startuml
'https://plantuml.com/sequence-diagram

autonumber

Player -> System: Start program
Player <- System: Ask about amount of players
Player -> System: Enter amount of players(numberOfPlayers)
      loop numberOfPlayers times
Player <-System: Ask for name of player
Player-> System: name of player(name)
end
Player -> System: play game








@enduml