@startuml
'https://plantuml.com/activity-diagram-beta

(*) --> "Land on Purchasable Field"
if "owned" then
   --> [true] "Pay the owner "
   -down->(*)
else
-->[false]  "Do you want to buy this field?"
if ""
--> [no] "ok"
->(*)
else
-->[yes] "Do you have enough money"
endif
if""
->[yes] "you now own this field"
->(*)
else
-->[no] "You dont have enough money"
->(*)
endif






@enduml
