@startuml
'https://plantuml.com/sequence-diagram


Actor Player
Player -> Main1 : Start game
activate Main1

Main1 -> Gamehandler : game.playGame();
activate Gamehandler
activate Settings
Gamehandler -> Settings : Settings.gameTextInit();
Settings -> TXTReaders : gameHandlerText = myTxtReader.reader("GameText");
activate TXTReaders

TXTReaders -> Settings : GameText.txt
deactivate TXTReaders
Settings -> Gamehandler
deactivate Settings
Gamehandler -> RaffleCup: private void roll(Player player)
activate RaffleCup
RaffleCup -> Gamehandler : public Rafflecup(int diceAmount, int faceAmount)
deactivate RaffleCup

Gamehandler -> Board :  public Board getmyBoard()
activate Board
Board -> Fields : public void landOn(Player player, GUIController gui)
Fields --> Gamehandler :
Gamehandler -> Players : player.changePosition(rafflecup.sum());
Players --> Gamehandler :
Gamehandler --> Gamehandler : private void takeTurn



Participant RaffleCup
Participant Board
Participant Players
Participant Settings
Collections Fields
Collections Chancecards
Collections TXTReaders


@enduml